import {
  Crown, Zap, Flame, Globe, Target, TrendingUp, Rocket,
  Heart, Gem, Telescope, ArrowLeftRight, ShieldCheck, Shield, Star, Database,
  Package, Layers, Trophy, Wallet, LayoutGrid, Sparkles, Footprints, Blocks,
  Activity, Smile, Repeat2, BadgeDollarSign, Send, Inbox, UserPlus, Users,
  Signal, ScanLine, Camera, Bot, Wand2, Upload, Timer, UserCheck, Medal,
  type LucideIcon,
} from "lucide-react";

export type Achievement = {
  id:            string;
  title:         string;
  description:   string;
  icon:          LucideIcon;
  status:        "unlocked" | "locked";
  /** Tailwind color class for icon when unlocked */
  color:         string;
  /** rgba() string used for box-shadow / border glow */
  glow:          string;
  unlockedAt?:   string;
  catalystItem?: { name: string; imageUrl: string };
};

// IDs that are pre-unlocked for the demo/investor account
export const DEMO_UNLOCKED_IDS = new Set([
  "heavyweight", "dealmaker", "first-blood", "high-roller", "early-adopter",
]);

export const ACHIEVEMENTS: Achievement[] = [
  // ── Demo showcase achievements (unlocked for demo account, locked for real users) ──
  {
    id:          "heavyweight",
    title:       "The Heavyweight",
    description: "Surpass $50,000 in total collection value",
    icon:        Crown,
    status:      "locked",
    color:       "text-[#D4AF37]",
    glow:        "rgba(212,175,55,0.35)",
    unlockedAt:  "Feb 12, 2026",
    catalystItem: {
      name:     "Rolex Datejust 41",
      imageUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=200&q=80",
    },
  },
  {
    id:          "dealmaker",
    title:       "Dealmaker",
    description: "Complete 10 successful trades",
    icon:        Zap,
    status:      "locked",
    color:       "text-primary",
    glow:        "rgba(202,230,206,0.3)",
    unlockedAt:  "Jan 3, 2026",
    catalystItem: {
      name:     "Mew ex SAR",
      imageUrl: "https://images.pokemontcg.io/sv3pt5/205_hires.png",
    },
  },
  {
    id:          "first-blood",
    title:       "First Blood",
    description: "Complete your very first trade",
    icon:        Flame,
    status:      "locked",
    color:       "text-orange-400",
    glow:        "rgba(251,146,60,0.35)",
    unlockedAt:  "Sep 14, 2024",
    catalystItem: {
      name:     "Charizard VMAX Rainbow",
      imageUrl: "https://images.pokemontcg.io/swsh35/74_hires.png",
    },
  },
  {
    id:          "high-roller",
    title:       "High Roller",
    description: "Propose a trade with a total value over $10,000",
    icon:        TrendingUp,
    status:      "locked",
    color:       "text-emerald-400",
    glow:        "rgba(52,211,153,0.3)",
    unlockedAt:  "Dec 1, 2025",
    catalystItem: {
      name:     "LEGO Millennium Falcon #75192",
      imageUrl: "https://cdn.rebrickable.com/media/sets/75192-1.jpg",
    },
  },
  // ── Always unlocked for every user ──────────────────────────────────────
  {
    id:          "early-adopter",
    title:       "Early Adopter",
    description: "Joined Uniques during the Beta phase",
    icon:        Rocket,
    status:      "unlocked",
    color:       "text-violet-400",
    glow:        "rgba(167,139,250,0.35)",
    unlockedAt:  "Aug 1, 2024",
  },
  // ── Locked ────────────────────────────────────────────────────────────
  {
    id:          "sniper",
    title:       "The Sniper",
    description: "Secure a Grail directly from your Radar",
    icon:        Target,
    status:      "locked",
    color:       "text-rose-400",
    glow:        "rgba(251,113,133,0.3)",
  },
  {
    id:          "worldwide",
    title:       "Mr. Worldwide",
    description: "Complete an international trade",
    icon:        Globe,
    status:      "locked",
    color:       "text-sky-400",
    glow:        "rgba(56,189,248,0.3)",
  },
  {
    id:          "curator",
    title:       "The Curator",
    description: "Add 50 items to your collection",
    icon:        Database,
    status:      "locked",
    color:       "text-purple-400",
    glow:        "rgba(192,132,252,0.3)",
  },
  {
    id:          "trendsetter",
    title:       "Trendsetter",
    description: "Receive 100 total likes across your Feed posts",
    icon:        Heart,
    status:      "locked",
    color:       "text-pink-400",
    glow:        "rgba(244,114,182,0.3)",
  },
  {
    id:          "diamond-hands",
    title:       "Diamond Hands",
    description: "Hold an item for over 1 year without trading it",
    icon:        Gem,
    status:      "locked",
    color:       "text-cyan-400",
    glow:        "rgba(34,211,238,0.3)",
  },
  {
    id:          "whale-watcher",
    title:       "Whale Watcher",
    description: "Follow 5 users with collections over $1M",
    icon:        Telescope,
    status:      "locked",
    color:       "text-blue-400",
    glow:        "rgba(96,165,250,0.3)",
  },
  {
    id:          "the-negotiator",
    title:       "The Negotiator",
    description: "Successfully counter-offer and close a deal",
    icon:        ArrowLeftRight,
    status:      "locked",
    color:       "text-amber-400",
    glow:        "rgba(251,191,36,0.3)",
  },
  {
    id:          "flawless",
    title:       "Flawless",
    description: "Own 10 items graded PSA 10 or BGS 9.5+",
    icon:        ShieldCheck,
    status:      "locked",
    color:       "text-teal-400",
    glow:        "rgba(45,212,191,0.3)",
  },
  {
    id:          "mint-condition",
    title:       "Mint Condition",
    description: "Add 5 PSA 10 graded items to your collection",
    icon:        Shield,
    status:      "locked",
    color:       "text-surface-light",
    glow:        "rgba(170,149,197,0.3)",
  },
  {
    id:          "completionist",
    title:       "Completionist",
    description: "Complete a full Pokémon set from a single era",
    icon:        Star,
    status:      "locked",
    color:       "text-yellow-300",
    glow:        "rgba(253,224,71,0.3)",
  },

  // ── Vault Building ─────────────────────────────────────────────────────────
  {
    id:          "first-relic",
    title:       "First Relic",
    description: "Add your first item to the vault",
    icon:        Package,
    status:      "locked",
    color:       "text-stone-400",
    glow:        "rgba(168,162,158,0.3)",
  },
  {
    id:          "growing-collection",
    title:       "Growing Collection",
    description: "Add 10 items to your vault",
    icon:        Layers,
    status:      "locked",
    color:       "text-lime-400",
    glow:        "rgba(163,230,53,0.3)",
  },
  {
    id:          "century-club",
    title:       "Century Club",
    description: "Add 100 items to your vault",
    icon:        Trophy,
    status:      "locked",
    color:       "text-yellow-400",
    glow:        "rgba(250,204,21,0.3)",
  },
  {
    id:          "five-figures",
    title:       "Five Figures",
    description: "Vault value reaches $10,000",
    icon:        TrendingUp,
    status:      "locked",
    color:       "text-green-400",
    glow:        "rgba(74,222,128,0.3)",
  },
  {
    id:          "six-figure-vault",
    title:       "Six-Figure Vault",
    description: "Vault value reaches $100,000",
    icon:        Wallet,
    status:      "locked",
    color:       "text-[#D4AF37]",
    glow:        "rgba(212,175,55,0.3)",
  },

  // ── Category Experts ───────────────────────────────────────────────────────
  {
    id:          "category-curious",
    title:       "Category Curious",
    description: "Own items in 3 different categories",
    icon:        LayoutGrid,
    status:      "locked",
    color:       "text-indigo-400",
    glow:        "rgba(129,140,248,0.3)",
  },
  {
    id:          "category-connoisseur",
    title:       "Category Connoisseur",
    description: "Own items in 5 different categories",
    icon:        LayoutGrid,
    status:      "locked",
    color:       "text-violet-300",
    glow:        "rgba(196,181,253,0.3)",
  },
  {
    id:          "pokemon-purist",
    title:       "Pokémon Purist",
    description: "Own 20+ Pokémon TCG items",
    icon:        Sparkles,
    status:      "locked",
    color:       "text-yellow-300",
    glow:        "rgba(253,224,71,0.35)",
  },
  {
    id:          "sneakerhead",
    title:       "Sneakerhead",
    description: "Own 10+ sneaker items",
    icon:        Footprints,
    status:      "locked",
    color:       "text-orange-300",
    glow:        "rgba(253,186,116,0.3)",
  },
  {
    id:          "brick-architect",
    title:       "Brick Architect",
    description: "Own 10+ LEGO sets",
    icon:        Blocks,
    status:      "locked",
    color:       "text-red-400",
    glow:        "rgba(248,113,113,0.3)",
  },
  {
    id:          "sports-fan",
    title:       "Sports Fan",
    description: "Own 10+ sports cards",
    icon:        Activity,
    status:      "locked",
    color:       "text-sky-300",
    glow:        "rgba(125,211,252,0.3)",
  },
  {
    id:          "funko-fanatic",
    title:       "Funko Fanatic",
    description: "Own 10+ Funko Pops",
    icon:        Smile,
    status:      "locked",
    color:       "text-fuchsia-400",
    glow:        "rgba(232,121,249,0.3)",
  },

  // ── Trading ────────────────────────────────────────────────────────────────
  {
    id:          "on-a-roll",
    title:       "On a Roll",
    description: "Complete 5 successful trades",
    icon:        Repeat2,
    status:      "locked",
    color:       "text-emerald-300",
    glow:        "rgba(110,231,183,0.3)",
  },
  {
    id:          "trading-machine",
    title:       "Trading Machine",
    description: "Complete 25 successful trades",
    icon:        Zap,
    status:      "locked",
    color:       "text-yellow-300",
    glow:        "rgba(253,224,71,0.3)",
  },
  {
    id:          "mega-deal",
    title:       "Mega Deal",
    description: "Complete a trade with total value over $25,000",
    icon:        BadgeDollarSign,
    status:      "locked",
    color:       "text-[#D4AF37]",
    glow:        "rgba(212,175,55,0.4)",
  },
  {
    id:          "first-offer",
    title:       "First Offer",
    description: "Send your first trade offer to someone",
    icon:        Send,
    status:      "locked",
    color:       "text-blue-300",
    glow:        "rgba(147,197,253,0.3)",
  },
  {
    id:          "popular-vault",
    title:       "Popular Vault",
    description: "Receive 5 trade offers in a single week",
    icon:        Inbox,
    status:      "locked",
    color:       "text-rose-300",
    glow:        "rgba(253,164,175,0.3)",
  },

  // ── Social ─────────────────────────────────────────────────────────────────
  {
    id:          "first-follow",
    title:       "First Follow",
    description: "Follow your first fellow collector",
    icon:        UserPlus,
    status:      "locked",
    color:       "text-teal-300",
    glow:        "rgba(94,234,212,0.3)",
  },
  {
    id:          "social-butterfly",
    title:       "Social Butterfly",
    description: "Follow 25 collectors",
    icon:        Users,
    status:      "locked",
    color:       "text-purple-300",
    glow:        "rgba(216,180,254,0.3)",
  },
  {
    id:          "influencer",
    title:       "Influencer",
    description: "Reach 50 followers",
    icon:        Signal,
    status:      "locked",
    color:       "text-pink-300",
    glow:        "rgba(249,168,212,0.3)",
  },

  // ── Magic AI ───────────────────────────────────────────────────────────────
  {
    id:          "first-scan",
    title:       "First Scan",
    description: "Use Magic AI Scan for the first time",
    icon:        ScanLine,
    status:      "locked",
    color:       "text-violet-300",
    glow:        "rgba(196,181,253,0.35)",
  },
  {
    id:          "scanner",
    title:       "Scanner",
    description: "Scan 10 items with Magic AI",
    icon:        Camera,
    status:      "locked",
    color:       "text-indigo-300",
    glow:        "rgba(165,180,252,0.3)",
  },
  {
    id:          "ai-addict",
    title:       "AI Addict",
    description: "Scan 50 items with Magic AI",
    icon:        Bot,
    status:      "locked",
    color:       "text-purple-400",
    glow:        "rgba(192,132,252,0.35)",
  },
  {
    id:          "grail-detected",
    title:       "Grail Detected",
    description: "Scan an item identified as worth $1,000+",
    icon:        Wand2,
    status:      "locked",
    color:       "text-amber-300",
    glow:        "rgba(252,211,77,0.4)",
  },
  {
    id:          "bulk-upload",
    title:       "Bulk Upload",
    description: "Add 10 items in a single day",
    icon:        Upload,
    status:      "locked",
    color:       "text-cyan-300",
    glow:        "rgba(103,232,249,0.3)",
  },
  {
    id:          "speedrunner",
    title:       "Speedrunner",
    description: "Add 25 items in a single week",
    icon:        Timer,
    status:      "locked",
    color:       "text-orange-400",
    glow:        "rgba(251,146,60,0.3)",
  },

  // ── Profile & Loyalty ──────────────────────────────────────────────────────
  {
    id:          "first-impression",
    title:       "First Impression",
    description: "Complete your profile with avatar, bio & handle",
    icon:        UserCheck,
    status:      "locked",
    color:       "text-green-300",
    glow:        "rgba(134,239,172,0.3)",
  },
  {
    id:          "pro-collector",
    title:       "Pro Collector",
    description: "Upgrade to Uniques Pro",
    icon:        Medal,
    status:      "locked",
    color:       "text-[#D4AF37]",
    glow:        "rgba(212,175,55,0.45)",
  },
];
