// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_DATABASE_URL for CLI (migrations, db push) if set,
    // otherwise fall back to DATABASE_URL (direct connection URL).
    // Rationale: in production the runtime DATABASE_URL may be the pooler
    // (port 6543 / pgbouncer mode) which doesn't support DDL/schema commands.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
